language: c
compiler:
  - gcc
install:
  - sudo apt-get install check
script:
  - gcc -o src/main.o src/main.c
  - gcc -std=c99 -o tests/array/check_bit_array.o tests/array/check_bit_array.c /src/main.c /src/array/bit_array.c
  - ./tests/array/check_bit_array.o
