language: c
compiler:
  - gcc
install:
  - sudo apt-get install check
script:
  - gcc -o src/main.o src/main.c
  - gcc -std=c99 -o check_bit_array.o check_bit_array.c ../../src/main.c ../../src/array/bit_array.c
  - ./main.o
