language: c
compiler:
  - gcc
install:
  - sudo apt-get install check
script:
  - gcc -o src/main.o src/*.c
  - ./src/main.o
  - chmod a+x os/*
  - ./os/c_array_tests.sh
  - ./os/array_tests.sh
  - ./os/utils_tests.sh
  - ./os/s_to_bwt_tests.sh
  - ./os/distinct_substrings_tests.sh
  - ./os/backward_search_tests.sh
