BW4SA: src/core/backward_search.h File Reference
backward_search.h File Reference
Contains functions for performing backward searches on strings in wavelet tree-form.
Functions
struct interval * backward_search (const struct wavelet_tree *bwt, const struct wavelet_tree *string, struct interval *target)
A function for finding the interval of given string in given BWT.
struct interval * backward_search_interval (const struct wavelet_tree *bwt, const struct interval *inter, char c, struct interval *target)
Finds the interval of a given letter of an interval in a BWT.
Detailed Description
Contains functions for performing backward searches on strings in wavelet tree-form.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
struct interval* backward_search (const struct wavelet_tree * bwt, const struct wavelet_tree * string, struct interval * target) [read]
A function for finding the interval of given string in given BWT.
Parameters:
bwt BWT of the string to be looked up, given in wavelet tree- form.*
string The string to be searched inside the BWT, given in wavelet tree-form.
target The interval-structure where the results should be stored. If NULL, a new interval-structure will be allocated and returned.
Returns:
The interval of the searched string inside the BWT, or NULL if it can't be found.
See also:
wavelet_tree.h
structs.h::interval
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
struct interval* backward_search_interval (const struct wavelet_tree * bwt, const struct interval * inter, char c, struct interval * target) [read]
Finds the interval of a given letter of an interval in a BWT.
Parameters:
bwt BWT of a string, given in wavelet tree-form.
inter Interval to be searched inside BWT.
c Character to be looked for inside the interval.
target The interval-structure where the results should be stored. If NULL, a new interval-structure will be allocated and returned.
Returns:
The interval of the searched character inside the BWT, or NULL if it can't be found.
See also:
backward_search
wavelet_tree.h
structs.h::interval
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by double_iterate(), list_mem_candidates(), map_maximal_repeats_to_string(), single_iterate(), and update_position_in_triplets().