BW4SA: src/utils/bit_vector.h File Reference
bit_vector.h File Reference
An array structure for storing strings compressed into integers.
#include <limits.h>
Data Structures
struct bit_vector
A structure for storing the bit vector and its manipulation-functions.
Defines
#define BITS_PER_INT (sizeof(unsigned int) * 8)
Typedefs
typedef struct bit_vector bit_vector
A structure for storing the bit vector and its manipulation-functions.
Functions
bit_vector * init_bit_vector (bit_vector *vector, unsigned int nbits)
Initializes the bit vector given as a parameter to a size of nbits.
void free_bit_vector (bit_vector *vector)
Frees the bit vector and all its internal variables.
Detailed Description
An array structure for storing strings compressed into integers.
This contains functions for creating, modifying and manipulating vector-like constructs that are intended for storing strings of text as compressed integers.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Typedef Documentation
typedef struct bit_vector bit_vector
A structure for storing the bit vector and its manipulation-functions.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
void free_bit_vector (bit_vector * vector)
Frees the bit vector and all its internal variables.
Parameters:
vector The vector that is to be destroyed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by print_mems().
bit_vector* init_bit_vector (bit_vector * vector, unsigned int nbits)
Initializes the bit vector given as a parameter to a size of nbits.
Initializes the bit vector given as a parameter to a size of nbits. Returns NULL if the vector given is NULL, nbits is 0 or the necessary space can't be successfully allocated.
Parameters:
vector The vector that is to be initialized.
nbits The amount of bits that should be allocated to the vector.
Returns:
The initialized vector, or NULL if any error occurred.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References get_bit_vector_length(), bit_vector::get_length, bit_vector::is_bit_marked, is_bit_marked(), bit_vector::mark_bit, mark_bit_vector_bit(), bit_vector::rank, rank_query(), bit_vector::unmark_bit, and unmark_bit_vector_bit().
Referenced by create_bit_vector(), max_repeat_make_bit_vector(), mem_make_bit_vectors(), mum_make_bit_vectors(), and print_tree_to_file().