BW4SA: src/utils/bit_vector.c File Reference
bit_vector.c File Reference
Implementation of the bit vector structure.
#include "bit_vector.h"
#include "utils.h"
#include <stdlib.h>
Functions
bit_vector * mark_bit_vector_bit (bit_vector *vector, unsigned int pos)
A function for marking a specific bit in a bit vector.
bit_vector * unmark_bit_vector_bit (bit_vector *vector, unsigned int pos)
A function for unmarking a bit inside a bitvector.
int is_bit_marked (const bit_vector *vector, unsigned int pos)
A function for checking if a bit is flagged.
unsigned int rank_query (const bit_vector *vector, unsigned int start, unsigned int end)
A simple rank-implementation.
unsigned int get_bit_vector_length (const bit_vector *vector)
Returns the length of the bit vector, i.e. the number of bits in it.
bit_vector * init_bit_vector (bit_vector *vector, unsigned int nbits)
Initializes the bit vector given as a parameter to a size of nbits.
void free_bit_vector (bit_vector *vector)
Frees the bit vector and all its internal variables.
Detailed Description
Implementation of the bit vector structure.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
void free_bit_vector (bit_vector * vector)
Frees the bit vector and all its internal variables.
Parameters:
vector The vector that is to be destroyed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by print_mems().
unsigned int get_bit_vector_length (const bit_vector * vector)
Returns the length of the bit vector, i.e. the number of bits in it.
Parameters:
vector The vector whose length is to be checked.
Returns:
The length of the bit vector, or the number of bits in it.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by init_bit_vector().
bit_vector* init_bit_vector (bit_vector * vector, unsigned int nbits)
Initializes the bit vector given as a parameter to a size of nbits.
Initializes the bit vector given as a parameter to a size of nbits. Returns NULL if the vector given is NULL, nbits is 0 or the necessary space can't be successfully allocated.
Parameters:
vector The vector that is to be initialized.
nbits The amount of bits that should be allocated to the vector.
Returns:
The initialized vector, or NULL if any error occurred.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References get_bit_vector_length(), bit_vector::get_length, bit_vector::is_bit_marked, is_bit_marked(), bit_vector::mark_bit, mark_bit_vector_bit(), bit_vector::rank, rank_query(), bit_vector::unmark_bit, and unmark_bit_vector_bit().
Referenced by create_bit_vector(), max_repeat_make_bit_vector(), mem_make_bit_vectors(), mum_make_bit_vectors(), and print_tree_to_file().
int is_bit_marked (const bit_vector * vector, unsigned int pos)
A function for checking if a bit is flagged.
This function checks if the bit at position pos is set in the vector supplied as parameter. It returns 1 if the bit is flagged, and 0 if the bit is not flagged or if pos is out of range.
Parameters:
vector The vector that is to be checked.
pos The position of the bit inside the vector.
Returns:
1 if the bit is found, 0 if it is not or if any internal errors occur.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by init_bit_vector().
bit_vector* mark_bit_vector_bit (bit_vector * vector, unsigned int pos)
A function for marking a specific bit in a bit vector.
This function marks a bit at position pos in the vector supplied as parameter. It is pointed to by every bit vector struct for easy access. The algorithm returns NULL if the vector is NULL or if pos is larger than the amount of bits stored in the vector.
Parameters:
vector The bit vector in which the bit to be manipulated lies.
pos The position of the bit inside the vector.
Returns:
The same vector supplied as parameter, or NULL if any internal conflicts occur.
See also:
unmark_bit_vector_bit
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by init_bit_vector().
unsigned int rank_query (const bit_vector * vector, unsigned int start, unsigned int end)
A simple rank-implementation.
This function returns the number of marked bits in the vector up to and including the position pos.
Parameters:
vector The vector that bits are going to be calculated for.
end The position after which the count should stop.
start The position where the count should start.
Returns:
The number of marked bits from start up to and including end.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::get_length, and bit_vector::is_bit_marked.
Referenced by init_bit_vector().
bit_vector* unmark_bit_vector_bit (bit_vector * vector, unsigned int pos)
A function for unmarking a bit inside a bitvector.
This function unmarks a bit at position pos in the vector supplied as parameter. It is pointed to by every bit vector struct for easy access. The algorithm returns NULL if the vector is NULL or if pos is larger than the amount of bits stored in the vector.
Parameters:
vector The bit vector in which the bit to be manipulated lies.
pos The position of the bit inside the vector.
Returns:
The same vector supplied as parameter, or NULL if any internal conflicts occur.
See also:
mark_bit_vector_bit
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by init_bit_vector().