BW4SA: src/core/c_array.h File Reference
c_array.h File Reference
A collection of functions for creating c-arrays and shortened alphabets.
Data Structures
struct alphabet_data
A simple struct for storing an alphabet as a string and its length.
Typedefs
typedef struct alphabet_data alphabet_data
A simple struct for storing an alphabet as a string and its length.
Functions
unsigned int * create_c_array (const struct wavelet_tree *string, const struct interval *inter, const char *alphabet, unsigned int alphabet_length, unsigned int *target)
Generates array C of given string in wavelet tree form.
alphabet_data * create_alphabet_interval (const struct interval *inter, const struct wavelet_tree *string, alphabet_data *target)
Generates the alphabet of a substring of a string.
Detailed Description
A collection of functions for creating c-arrays and shortened alphabets.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Data Structure Documentation
struct alphabet_data
A simple struct for storing an alphabet as a string and its length.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Data Fields
char * alphabet
unsigned int length
Typedef Documentation
typedef struct alphabet_data alphabet_data
A simple struct for storing an alphabet as a string and its length.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
alphabet_data* create_alphabet_interval (const struct interval * inter, const struct wavelet_tree * string, alphabet_data * target)
Generates the alphabet of a substring of a string.
Parameters:
inter The starting and ending indices of the substring inside the string, stored in an interval-struct.
string The string, in wavelet tree form, from which the substring is to be determined.
target The structure where the results should be stored. If NULL, a new alphabet_data-struct will be allocated and returned.
Returns:
The alphabet used by the substring.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by double_iterate(), list_mem_candidates(), and single_iterate().
unsigned int* create_c_array (const struct wavelet_tree * string, const struct interval * inter, const char * alphabet, unsigned int alphabet_length, unsigned int * target)
Generates array C of given string in wavelet tree form.
A c-array is an array of indexes to the starting location inside a BWT of each distinct character used by the BWT, ordered lexicographically.
Parameters:
string The string in wavelet tree form from which a c-array should be generated.
inter An interval of the substring from which the c-array should be generated. If NULL, the entire string is used.
alphabet The alphabet used by the string. If NULL, the alphabet of the wavelet tree is used.
alphabet_length Length of the alphabet supplied as parameter. If the alphabet is NULL, this parameter will be disregarded.
target An unsigned integer array where the results should be stored. If target is NULL, a new array will be allocated and returned instead.
Returns:
Array C which contains starting indexes of each distinct character used in the alphabet.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by double_iterate(), list_mem_candidates(), and single_iterate().