BW4SA: src/applications/draw_tree.h File Reference
draw_tree.h File Reference
A function for writing a suffix tree in dot-format to a file.
Functions
void draw_suffix_tree (char *string, char *filename)
Writes a suffix tree of the given string in dot format to a file.
Detailed Description
A function for writing a suffix tree in dot-format to a file.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
void draw_suffix_tree (char * string, char * filename)
Writes a suffix tree of the given string in dot format to a file.
Parameters:
string The string to be written.
filename The path to the file to be written to.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References free_wavelet_tree(), iterate(), map_create_suffix_array_from_bwt(), print_tree_to_file(), and s_to_bwt().