BW4SA: src/applications/draw_tree.c File Reference
draw_tree.c File Reference
Implementation of dot-tree drawing functions.
#include "draw_tree.h"
#include "map_bwt_to_s.h"
#include "../core/iterate.h"
#include "../core/c_array.h"
#include "../core/backward_search.h"
#include "../core/s_to_bwt.h"
#include "../utils/bit_vector.h"
#include "../../include/utils.h"
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct i_node
A struct for storing a suffix tree node and its data.
struct tree_results
Typedefs
typedef struct i_node internal_node
A struct for storing a suffix tree node and its data.
typedef struct tree_results tree_results
Functions
int is_child (substring *parent, substring *child)
A function for checking if a substring is a substring of another substring.
int substring_and_node_equal (substring *substr, internal_node *node)
A simple function that checks if a substring is the same as one stored in a node.
internal_node * find_node_by_substring (substring *substr, internal_node *root)
A function for finding a node inside the tree based on a substring.
void collect_internal_nodes (iterator_state *state, void *results)
Inserts a new node into the dot tree as a callback-function to iterate.
void print_node_label_to_file (FILE *f, internal_node *node)
Prints a label of a node to a file.
void print_arcs (FILE *f, internal_node *node)
Prints the outgoing arcs of a node to a file.
void print_arcs_recursively (FILE *f, internal_node *node)
A function for printing the arcs of an entire suffix tree to a file recursively.
void print_leaves_recursively (FILE *f, internal_node *node, int *suffix_array, char *orig_string, bit_vector *leaf_vec)
A function for printing leaf nodes of a suffix tree to a file recursively.
void print_weiner_links (internal_node *node, FILE *f)
Prints the Weiner-links of a node to a file.
void print_weiner_links_recursively (FILE *f, internal_node *node)
Prints all the Weiner-links of a suffix tree to a file recursively.
void print_tree_to_file (char *filename, int *suffix_array, char *orig_string, internal_node *root)
Prints a suffix tree in dot-format to a file.
parameter_struct * initialize_for_tree_drawing (char **strings)
void draw_suffix_tree (char *string, char *filename)
Writes a suffix tree of the given string in dot format to a file.
Detailed Description
Implementation of dot-tree drawing functions.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Data Structure Documentation
struct i_node
A struct for storing a suffix tree node and its data.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Data Fields
char c
struct i_node * first_child
int id
struct i_node * next_sibling
struct i_node * parent
struct i_node * previous_sibling
substring * substr
struct i_node * weiner_node
struct tree_results
Data Fields
int node_index
internal_node * root
Typedef Documentation
typedef struct i_node internal_node
A struct for storing a suffix tree node and its data.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
void collect_internal_nodes (iterator_state * state, void * results)
Inserts a new node into the dot tree as a callback-function to iterate.
Parameters:
state The internal state of the iterator.
results A pointer to a region of memory containing any previous results stored by this callback (not used in this function).
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::current, iterator_state::current_extension, find_node_by_substring(), is_child(), and iterator_state::prev.
void draw_suffix_tree (char * string, char * filename)
Writes a suffix tree of the given string in dot format to a file.
Parameters:
string The string to be written.
filename The path to the file to be written to.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References free_wavelet_tree(), iterate(), map_create_suffix_array_from_bwt(), print_tree_to_file(), and s_to_bwt().
internal_node* find_node_by_substring (substring * substr, internal_node * root)
A function for finding a node inside the tree based on a substring.
Parameters:
substr The substring to be searched for.
Returns:
Returns the node containing the substring, or NULL if no node matching the substring could be found.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References is_child(), and substring_and_node_equal().
Referenced by collect_internal_nodes().
int is_child (substring * parent, substring * child)
A function for checking if a substring is a substring of another substring.
Parameters:
parent The suspected parent of the other substring.
child The suspected child of the other substring.
Returns:
Returns 1 if child is inside (in other words a child) of parent, otherwise returns 0.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by collect_internal_nodes(), and find_node_by_substring().
void print_arcs (FILE * f, internal_node * node)
Prints the outgoing arcs of a node to a file.
Parameters:
f The file to be printed to.
node The node to be printed to a file.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References print_node_label_to_file().
Referenced by print_arcs_recursively().
void print_arcs_recursively (FILE * f, internal_node * node)
A function for printing the arcs of an entire suffix tree to a file recursively.
Parameters:
f The file to be printed to.
node The root of the tree to be printed to a file.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References print_arcs().
Referenced by print_tree_to_file().
void print_leaves_recursively (FILE * f, internal_node * node, int * suffix_array, char * orig_string, bit_vector * leaf_vec)
A function for printing leaf nodes of a suffix tree to a file recursively.
Parameters:
f The file to be printed to.
node A node that is to be checked if its a leaf node.
suffix_array A suffix array for creating a substring.
orig_string The entire original string that the tree was created of as a character sequence.
leaf_vec A bit vector for checking which characters of the original string should be printed.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::is_bit_marked, and bit_vector::mark_bit.
Referenced by print_tree_to_file().
void print_node_label_to_file (FILE * f, internal_node * node)
Prints a label of a node to a file.
Parameters:
f The file to be printed to.
node The node to be printed to a file.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by print_arcs().
void print_tree_to_file (char * filename, int * suffix_array, char * orig_string, internal_node * root)
Prints a suffix tree in dot-format to a file.
Parameters:
filename The path to the file to be printed to.
suffix_array The suffix array of the suffix tree.
orig_string The original string used for creating the suffix tree.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References init_bit_vector(), print_arcs_recursively(), print_leaves_recursively(), and print_weiner_links_recursively().
Referenced by draw_suffix_tree().
void print_weiner_links (internal_node * node, FILE * f)
Prints the Weiner-links of a node to a file.
Parameters:
node The node whose Weiner-links are to be printed.
f The file to be printed to.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by print_weiner_links_recursively().
void print_weiner_links_recursively (FILE * f, internal_node * node)
Prints all the Weiner-links of a suffix tree to a file recursively.
Parameters:
f The file to be printed to.
node The root of the tree to be printed to a file.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References print_weiner_links().
Referenced by print_tree_to_file().
int substring_and_node_equal (substring * substr, internal_node * node)
A simple function that checks if a substring is the same as one stored in a node.
Parameters:
substr The substring to be compared to the one stored in a node.
node The node storing a substring to be compared to the other substring.
Returns:
Returns 1 if the substrings are equals, 0 otherwise.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by find_node_by_substring().