BW4SA: src/core/iterate.h File Reference
iterate.h File Reference
The core of the entire library.
Data Structures
struct iterator_state
A structure for storing the internal state of an iterator.
struct parameter_struct
A struct for storing the parameters given to iterate.
Defines
#define MAX_REPEATS 0
#define MUM 1
#define MEM 2
#define DOT_TREE 3
Typedefs
typedef unsigned int iterate_t
Unsigned int typedefed as the type of iterate that is to be performed.
typedef struct iterator_state iterator_state
A structure for storing the internal state of an iterator.
typedef struct parameter_struct parameter_struct
A struct for storing the parameters given to iterate.
Functions
iterator_state * initialize_iterator (char **strings, unsigned int num_strings)
Initializes the iterator's internal state.
void free_iterator_state (iterator_state *state)
Frees an iterator_state-structure and all it's resources.
void free_parameter_struct (parameter_struct *params)
Frees a parameter_struct-structure and all it's resources, except for the return data.
iterator_state * iterate (parameter_struct *parameters)
The main iteration function.
void * single_iterate (iterator_state *state, void(*callback)(iterator_state *state, void *results), void *result)
A function for iterating through right maximal substrings of a string.
void * double_iterate (iterator_state *state, void(*callback)(iterator_state *state, void *results), void *result)
A function for simultaneously iterating over two strings.
Detailed Description
The core of the entire library.
This file contains all functions for iterating through strings and collecting data on the strings.
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator), Paula Lehtola
Bug:
No known bugs.
Data Structure Documentation
struct iterator_state
A structure for storing the internal state of an iterator.
Author:
Max Sandberg (REXiator)
Data Fields
struct alphabet_data * alpha_datas Current alphabets over intervals inside the BWT's.
struct wavelet_tree * bwts All BWT's used by this iterator.
unsigned int ** c_arrays All the c-arrays used by the iterator in this iteration.
struct alphabet_data * common_alphabet The common alphabet shared by all strings. NULL if only one string.
struct substring * current All the substrings that have been found in this iteration step.
char current_extension The current extension character in the iteration process.
struct interval * normals All the intervals on the BWT's that are used in this iteration by the iterator.
unsigned int num_strings The number of strings that the iterator is iterating over.
struct substring * prev All the substrings that have been found in the previous iteration step.
struct wavelet_tree * reverse_bwts All BWT's of the reversed strings used by this iterator.
struct bit_vector * reverse_runs_vectors All runs vectors of the reverse strings used by this iterator.
struct interval * reverses All the intervals on the reverse BWT's that are used in this iteration by the iterator.
struct bit_vector * runs_vectors All runs vectors used by this iterator.
struct substring_stack * stacks All substring stacks used by this iterator.
int threshold Length of the shortest string the callback function will process.
Typedef Documentation
typedef unsigned int iterate_t
Unsigned int typedefed as the type of iterate that is to be performed.
Author:
Max Sandberg (REXiator)
typedef struct iterator_state iterator_state
A structure for storing the internal state of an iterator.
Author:
Max Sandberg (REXiator)
typedef struct parameter_struct parameter_struct
A struct for storing the parameters given to iterate.
Author:
Max Sandberg (REXiator)
Function Documentation
void* double_iterate (iterator_state * state, void(*)(iterator_state *state, void *results) callback, void * result)
A function for simultaneously iterating over two strings.
Parameters:
state The internal variables used by the iteration function.
callback The callback function to be called whenever matching substrings inside both strings are found to be right maximal.
result A pointer to a region of memory where the callback-function can store its results.
Returns:
Returns a pointer to the results of the iteration process.
See also:
iterate
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::alpha_datas, backward_search_interval(), iterator_state::bwts, iterator_state::c_arrays, combine_alphabets_intersection(), iterator_state::common_alphabet, create_alphabet_interval(), create_c_array(), create_substring(), iterator_state::current, iterator_state::current_extension, wavelet_tree::get_num_bits, iterator_state::normals, pop(), iterator_state::prev, push(), iterator_state::reverse_bwts, iterator_state::reverse_runs_vectors, iterator_state::reverses, iterator_state::stacks, and update_reverse_interval().
Referenced by iterate().
void free_iterator_state (iterator_state * state)
Frees an iterator_state-structure and all it's resources.
Parameters:
state The structure to be freed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::alpha_datas, iterator_state::bwts, iterator_state::c_arrays, iterator_state::common_alphabet, iterator_state::current, free_wavelet_tree_internals(), iterator_state::normals, iterator_state::num_strings, iterator_state::prev, iterator_state::reverse_bwts, iterator_state::reverse_runs_vectors, iterator_state::reverses, iterator_state::runs_vectors, and iterator_state::stacks.
void free_parameter_struct (parameter_struct * params)
Frees a parameter_struct-structure and all it's resources, except for the return data.
Parameters:
params The structure to be freed.
Author:
Max Sandberg (REXiator)
Bug:
Throws errors if strings have not been allocated on the heap.
iterator_state* initialize_iterator (char ** strings, unsigned int num_strings)
Initializes the iterator's internal state.
Parameters:
strings A list of pointers to strings that are to be iterated over.
num_strings The number of strings inside the list.
Returns:
An initialized iterator_state-pointer.
See also:
iterator_state
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::alpha_datas, iterator_state::bwts, iterator_state::c_arrays, iterator_state::common_alphabet, create_stack(), iterator_state::current, wavelet_tree::get_alphabet_length, iterator_state::normals, iterator_state::num_strings, iterator_state::prev, reverse_bwt(), iterator_state::reverse_bwts, iterator_state::reverse_runs_vectors, iterator_state::reverses, iterator_state::runs_vectors, s_to_bwt(), and iterator_state::stacks.
Referenced by iterate().
iterator_state* iterate (parameter_struct * parameters)
The main iteration function.
Determines what kind of iterate-function to call based on the parameters sent to it. Should always be initialized using one of the initialization-functions found in any of the files in the applications-folder.
Parameters:
parameters The parameters used to determine what kind of iteration to perform.
Returns:
The internal state of the iterator after the iteration is done.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References double_iterate(), initialize_iterator(), single_iterate(), and iterator_state::threshold.
Referenced by draw_suffix_tree().
void* single_iterate (iterator_state * state, void(*)(iterator_state *state, void *results) callback, void * result)
A function for iterating through right maximal substrings of a string.
Creates a BWT of a string and iterates through substrings of it. If the substring is right maximal, the callback function given as parameter will be called on the substring.
Parameters:
state The internal variables used by the iteration function.
callback Function pointer to a callback function that is to be called on each right maximal substring.
result A pointer to a region of memory where the callback-function can store its results.
Returns:
Returns a pointer to the results of the iteration process.
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::alpha_datas, backward_search_interval(), iterator_state::bwts, iterator_state::c_arrays, create_alphabet_interval(), create_c_array(), create_substring(), iterator_state::current, iterator_state::current_extension, wavelet_tree::get_num_bits, is_reverse_interval_right_maximal(), iterator_state::normals, pop(), iterator_state::prev, push(), reverse_bwt(), iterator_state::reverse_bwts, iterator_state::reverse_runs_vectors, iterator_state::reverses, iterator_state::stacks, and update_reverse_interval().
Referenced by iterate().