BW4SA: src/applications/mapper.c File Reference
mapper.c File Reference
Implementation of the mapping functions.
#include "mapper.h"
#include "maximal_repeats.h"
#include "mum.h"
#include "triplet_sorter.h"
#include "../../include/utils.h"
#include "../core/backward_search.h"
#include <stdlib.h>
#include <string.h>
Functions
int marked_bits_on_bit_vector (bit_vector *vec, int vector_length)
A function that counts the number of marked bits.
max_repeat_with_indexes * map_maximal_repeats_to_string (max_repeat_node *nodes, wavelet_tree *bwt, int nodes_length, bit_vector *bit_vec)
Maps the BWT indexes to indexes in the original string in all found maximal repeats.
mapped_pair * update_position_in_triplets (wavelet_tree *bwt, int nodes_length, bit_vector *bit_vec, int marked_bits)
A function for mapping the indices inside the BWT to indices inside the original c-string.
void map_mum_triplets_to_string (triplet *nodes, wavelet_tree *bwt1, wavelet_tree *bwt2, int nodes_length, bit_vector **vecs)
Maps the BWT indexes to indexes in the original string in all found MUMs.
void map_mem_triplets_to_string (triplet *nodes, wavelet_tree *bwt1, wavelet_tree *bwt2, int nodes_length, bit_vector **vecs)
Maps the BWT indexes to indexes in the original string in all found MEMs.
Detailed Description
Implementation of the mapping functions.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator), Paula Lehtola
Bug:
No known bugs.
Function Documentation
max_repeat_with_indexes* map_maximal_repeats_to_string (struct max_repeat_node * nodes, struct wavelet_tree * bwt, int nodes_length, struct bit_vector * bit_vec)
Maps the BWT indexes to indexes in the original string in all found maximal repeats.
Updates the normal.i value to index in the original string.
Parameters:
nodes An array of all maximal repeat substrings inside the BWT.
bwt The BWT of the original string, in wavelet tree form.
nodes_length Length of the nodes-array.
bit_vec Bit vector which tells where the maximals repeats start
Returns:
A list of maximal repeats with all occurrences
Author:
Lassi Vapaakallio, Max Sandberg (REXiator), Paula Lehtola
Bug:
No known bugs.
References backward_search_interval(), wavelet_tree::char_at, wavelet_tree::get_num_bits, bit_vector::is_bit_marked, marked_bits_on_bit_vector(), and quick_sort().
Referenced by print_maximal_repeat_substrings().
void map_mem_triplets_to_string (struct triplet * nodes, struct wavelet_tree * bwt1, struct wavelet_tree * bwt2, int nodes_length, struct bit_vector ** vecs)
Maps the BWT indexes to indexes in the original string in all found MEMs.
Updates the position values in both strings to indexes in the original string.
Parameters:
nodes An array of all triplets returned after iteration.
bwt1 BWT of the first string.
bwt2 BWT of the second string.
nodes_length Length of the array of nodes.
vecs Bit vector containing the starting position of MEMs in both strings
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References wavelet_tree::get_num_bits, marked_bits_on_bit_vector(), and update_position_in_triplets().
Referenced by print_mems().
void map_mum_triplets_to_string (struct triplet * nodes, struct wavelet_tree * bwt1, struct wavelet_tree * bwt2, int nodes_length, struct bit_vector ** vecs)
Maps the BWT indexes to indexes in the original string in all found MUMs.
Updates the position values in both strings to indexes in the original string.
Parameters:
nodes An array of all triplets returned after iteration.
bwt1 BWT of the first string.
bwt2 BWT of the second string.
nodes_length Length of the array of nodes.
vecs Bit vector containing the starting position of MUMs in both strings
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References wavelet_tree::get_num_bits, marked_bits_on_bit_vector(), and update_position_in_triplets().
Referenced by print_mums().
int marked_bits_on_bit_vector (bit_vector * vec, int vector_length)
A function that counts the number of marked bits.
Parameters:
vector_length Length of the bit vector.
bit_vec Bit vector to be counted from
Author:
Lassi Vapaakallio, Paula Lehtola
Bug:
No known bugs.
References bit_vector::is_bit_marked.
Referenced by map_maximal_repeats_to_string(), map_mem_triplets_to_string(), and map_mum_triplets_to_string().
mapped_pair* update_position_in_triplets (wavelet_tree * bwt, int nodes_length, bit_vector * bit_vec, int marked_bits)
A function for mapping the indices inside the BWT to indices inside the original c-string.
Parameters:
bwt The BWT of a string, represented as a wavelet tree.
nodes_length Length of the array.
bit_vec Bit vector containing the mappable indexes
marked_bits number of bits marked in the vector
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References backward_search_interval(), wavelet_tree::char_at, wavelet_tree::get_num_bits, and bit_vector::is_bit_marked.
Referenced by map_mem_triplets_to_string(), and map_mum_triplets_to_string().