BW4SA: src/applications/maximal_repeats.c File Reference
maximal_repeats.c File Reference
Implementation of the functions related to maximal repeats.
#include "maximal_repeats.h"
#include "map_bwt_to_s.h"
#include "mapper.h"
#include "../core/iterate.h"
#include "../../include/utils.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Functions
parameter_struct * initialize_for_max_repeats (char *string, int threshold)
An initialization function that creates a parameter struct that instructs iterate to search for maximal repeats.
int is_interval_left_maximal (bit_vector *runs, interval inter)
A simple function for determining if an interval is right maximal.
void search_maximal_repeats (iterator_state *state, void *results)
The function given as callback to iterate for finding maximal repeats.
void print_maximal_repeat_substrings (char *string, max_repeat_results *results, iterator_state *state)
Prints the substring the interval represents.
bit_vector * max_repeat_make_bit_vector (max_repeat_results *results, iterator_state *state)
Creates a bit vectors based on the given string, where marked bits correspond to starting indexes of maximal repeats inside the string.
Detailed Description
Implementation of the functions related to maximal repeats.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
parameter_struct* initialize_for_max_repeats (char * string, int threshold) [read]
An initialization function that creates a parameter struct that instructs iterate to search for maximal repeats.
Parameters:
string The string that should be iterated over.
Returns:
An initialized parameter struct ready to be passed to iterate.
See also:
iterate.h::parameter_struct
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References search_maximal_repeats().
int is_interval_left_maximal (bit_vector * runs, interval inter)
A simple function for determining if an interval is right maximal.
Parameters:
runs The runs vector for the BWT of a string.
inter The interval to be checked.
Returns:
1 if the interval is a maximal repeat, 0 otherwise.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::rank.
Referenced by search_maximal_repeats().
bit_vector* max_repeat_make_bit_vector (max_repeat_results * results, struct iterator_state * state) [read]
Creates a bit vectors based on the given string, where marked bits correspond to starting indexes of maximal repeats inside the string.
Parameters:
results The results of an iteration over a set of strings.
state Internal state of the iterator that performed the search.
Returns:
Bit vectors with starts of Maximal repeats marked.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, wavelet_tree::get_num_bits, init_bit_vector(), and bit_vector::mark_bit.
Referenced by print_maximal_repeat_substrings().
void print_maximal_repeat_substrings (char * string, max_repeat_results * results, struct iterator_state * state)
Prints the substring the interval represents.
First uses the mapper-function map_maximal_repeats_to_string() and then prints the substring based on the mapped index to stdout.
Parameters:
string The original c-string.
results Results of iterating over the c-string to find maximal repeats.
state The internal state of the iterator performing the search.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, map_maximal_repeats_to_string(), and max_repeat_make_bit_vector().
void search_maximal_repeats (struct iterator_state * state, void * results)
The function given as callback to iterate for finding maximal repeats.
Determines if a node is a maximal repeat and adds it to a list.
Parameters:
state The internal state of the iterator.
results A pointer to a region of memory where previous results for this function can be found. Can safely be cast to max_repeat_results if iterate was initialized using initialize_for_max_repeats().
See also:
initialize_for_max_repeats
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::current, is_interval_left_maximal(), iterator_state::runs_vectors, and iterator_state::threshold.
Referenced by initialize_for_max_repeats().