BW4SA: src/applications/mems.h File Reference
mems.h File Reference
A collection of functions for finding Maximal Exact Matches (=MEMs) using iterate.
#include "../utils/structs.h"
#include "../core/iterate.h"
Data Structures
struct mem_results
A structure for storing the results of an iteration when finding maximal exact matches.
Typedefs
typedef struct mem_results mem_results
A structure for storing the results of an iteration when finding maximal exact matches.
Functions
struct parameter_struct * initialize_for_mems (char **strings, int max_number_mems)
An initialization function that creates a parameter struct that instructs iterate to search for maximal exact matches.
void search_mems (struct iterator_state *state, void *results)
Callback function given to double_iterate that determines if a substring is a MEM (Maximal Exact Match)
void print_mems (char *string, mem_results *results, iterator_state *state)
Prints the indexes of the MEM in both strings, as well as the substring itself, to stdout.
struct bit_vector ** mem_make_bit_vectors (mem_results *results, struct iterator_state *state)
Creates a list of two bit vectors based on the given strings, where marked bits correspond to starting indexes of MEM's inside the strings.
Detailed Description
A collection of functions for finding Maximal Exact Matches (=MEMs) using iterate.
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Data Structure Documentation
struct mem_results
A structure for storing the results of an iteration when finding maximal exact matches.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Data Fields
unsigned int allocated_length
triplet * data
unsigned int length
void * params
Typedef Documentation
typedef struct mem_results mem_results
A structure for storing the results of an iteration when finding maximal exact matches.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
struct parameter_struct* initialize_for_mems (char ** strings, int max_number_mems) [read]
An initialization function that creates a parameter struct that instructs iterate to search for maximal exact matches.
Parameters:
strings An array of pointers to strings that are to be iterated over.
max_number_mems Number of slots of memory allocated for triplets. This number has to be at least as large as expected number of MEMs.
Returns:
An initialized parameter struct ready to be passed to iterate.
Author:
Max Sandberg (REXiator), Topi Paavilainen
Bug:
No known bugs.
References search_mems().
struct bit_vector** mem_make_bit_vectors (mem_results * results, struct iterator_state * state) [read]
Creates a list of two bit vectors based on the given strings, where marked bits correspond to starting indexes of MEM's inside the strings.
Parameters:
results The results of an iteration over a set of strings.
state Internal state of the iterator that performed the search.
Returns:
Bit vectors with starts of MEMs marked.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, wavelet_tree::get_num_bits, init_bit_vector(), and bit_vector::mark_bit.
Referenced by print_mems().
void print_mems (char * string, mem_results * results, iterator_state * state)
Prints the indexes of the MEM in both strings, as well as the substring itself, to stdout.
Parameters:
string The string that is to be searched inside the MEM.
results Results of the iteration over a set of strings.
state The internal state of the iterator that performed the search.
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, free_bit_vector(), map_mem_triplets_to_string(), mem_make_bit_vectors(), and substring_from_string().
void search_mems (struct iterator_state * state, void * results)
Callback function given to double_iterate that determines if a substring is a MEM (Maximal Exact Match)
Parameters:
state The internal state of the iterator.
results A pointer to a region of memory containing the previous results of this callback function. Can safely be cast to mem_results if iterate was initialized using initialize_for_mems().
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, iterator_state::current, list_mem_candidates(), iterator_state::reverse_bwts, and iterator_state::threshold.
Referenced by initialize_for_mems().