BW4SA: src/applications/mems.c File Reference
mems.c File Reference
Implementation of the functions for finding MEMs using iterate.
#include "mems.h"
#include "../../include/utils.h"
#include "../../include/core.h"
#include "../../include/applications.h"
#include "../core/c_array.h"
#include "../core/backward_search.h"
#include "mapper.h"
#include <stdlib.h>
#include <stdio.h>
Data Structures
struct mem_candidate
A structure for storing a possible MEM.
struct mem_parameters
A structure for storing the variables used by the MEM-search.
Typedefs
typedef struct mem_candidate mem_candidate
A structure for storing a possible MEM.
typedef struct mem_parameters mem_parameters
A structure for storing the variables used by the MEM-search.
Functions
parameter_struct * initialize_for_mems (char **strings, int threshold)
An initialization function that creates a parameter struct that instructs iterate to search for maximal exact matches.
int list_mem_candidates (substring *node, wavelet_tree *bwt, wavelet_tree *rbwt, mem_candidate *mem_candidates, mem_parameters *mem_params)
A function for finding potential MEMs.
void search_mems (iterator_state *state, void *results)
Callback function given to double_iterate that determines if a substring is a MEM (Maximal Exact Match)
void print_mems (char *string, mem_results *results, iterator_state *state)
Prints the indexes of the MEM in both strings, as well as the substring itself, to stdout.
bit_vector ** mem_make_bit_vectors (mem_results *results, iterator_state *state)
Creates a list of two bit vectors based on the given strings, where marked bits correspond to starting indexes of MEM's inside the strings.
Detailed Description
Implementation of the functions for finding MEMs using iterate.
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Data Structure Documentation
struct mem_candidate
A structure for storing a possible MEM.
Author:
Topi Paavilainen
Data Fields
substring extension
char first
char last
struct mem_parameters
A structure for storing the variables used by the MEM-search.
Author:
Max Sandberg (REXiator)
Data Fields
alphabet_data alpha_data_left
alphabet_data alpha_data_right
interval normal_left
interval normal_right
interval reverse_left
interval reverse_right
Typedef Documentation
typedef struct mem_candidate mem_candidate
A structure for storing a possible MEM.
Author:
Topi Paavilainen
typedef struct mem_parameters mem_parameters
A structure for storing the variables used by the MEM-search.
Author:
Max Sandberg (REXiator)
Function Documentation
parameter_struct* initialize_for_mems (char ** strings, int max_number_mems) [read]
An initialization function that creates a parameter struct that instructs iterate to search for maximal exact matches.
Parameters:
strings An array of pointers to strings that are to be iterated over.
max_number_mems Number of slots of memory allocated for triplets. This number has to be at least as large as expected number of MEMs.
Returns:
An initialized parameter struct ready to be passed to iterate.
Author:
Max Sandberg (REXiator), Topi Paavilainen
Bug:
No known bugs.
References search_mems().
int list_mem_candidates (substring * node, wavelet_tree * bwt, wavelet_tree * rbwt, mem_candidate * mem_candidates, mem_parameters * mem_params)
A function for finding potential MEMs.
Parameters:
node The current substring being searched.
bwt The BWT of a string, represented as a wavelet tree.
rbwt The BWT of the reverse of a string, represented as a wavelet tree.
mem_candidates The current list of possible MEMs being searched.
mem_params The parameters used by the MEM search.
Returns:
Returns the length of the list of MEM candidates.
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References backward_search_interval(), create_alphabet_interval(), create_c_array(), create_substring(), wavelet_tree::get_alphabet_length, and update_reverse_interval().
Referenced by search_mems().
bit_vector** mem_make_bit_vectors (mem_results * results, struct iterator_state * state) [read]
Creates a list of two bit vectors based on the given strings, where marked bits correspond to starting indexes of MEM's inside the strings.
Parameters:
results The results of an iteration over a set of strings.
state Internal state of the iterator that performed the search.
Returns:
Bit vectors with starts of MEMs marked.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, wavelet_tree::get_num_bits, init_bit_vector(), and bit_vector::mark_bit.
Referenced by print_mems().
void print_mems (char * string, mem_results * results, iterator_state * state)
Prints the indexes of the MEM in both strings, as well as the substring itself, to stdout.
Parameters:
string The string that is to be searched inside the MEM.
results Results of the iteration over a set of strings.
state The internal state of the iterator that performed the search.
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, free_bit_vector(), map_mem_triplets_to_string(), mem_make_bit_vectors(), and substring_from_string().
void search_mems (struct iterator_state * state, void * results)
Callback function given to double_iterate that determines if a substring is a MEM (Maximal Exact Match)
Parameters:
state The internal state of the iterator.
results A pointer to a region of memory containing the previous results of this callback function. Can safely be cast to mem_results if iterate was initialized using initialize_for_mems().
Author:
Lassi Vapaakallio, Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, iterator_state::current, list_mem_candidates(), iterator_state::reverse_bwts, and iterator_state::threshold.
Referenced by initialize_for_mems().