BW4SA: src/applications/mum.c File Reference
mum.c File Reference
Implementation of the algorithms related to maximal unique matches.
#include "mum.h"
#include "mapper.h"
#include "../core/iterate.h"
#include "../../include/utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
parameter_struct * initialize_for_mums (char **strings, int threshold)
An initialization function that creates a parameter struct that instructs iterate to search for maximal unique matches.
void search_mums (iterator_state *state, void *results)
Callback function given to double_iterate that determines if a substring is a MUM.
void print_mums (char *string, mum_results *results, iterator_state *state)
Prints the indexes of the MUM in both strings, as well as the substring itself, to stdout.
bit_vector ** mum_make_bit_vectors (mum_results *results, iterator_state *state)
Creates a list of two bit vectors based on the given strings, where marked bits correspond to starting indexes of MUM's inside the strings.
void print_bit_vector_with_string (char *string1, bit_vector *vector)
A simple function for printing a bit vector with the c-string that is related to it to stdout.
void mum_print_bit_vectors (char *string1, char *string2, mum_results *results, iterator_state *state)
Prints the bit vectors of the strings which show where MUMs occur to stdout.
Detailed Description
Implementation of the algorithms related to maximal unique matches.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
parameter_struct* initialize_for_mums (char ** strings, int threshold) [read]
An initialization function that creates a parameter struct that instructs iterate to search for maximal unique matches.
Parameters:
strings An array of pointers to strings that are to be iterated over.
max_number_mums number of slots of memory allocated for triplets. This number has to be at least as large as expected number of MUMs.
Returns:
An initialized parameter struct ready to be passed to iterate.
Author:
Max Sandberg (REXiator), Topi Paavilainen
Bug:
No known bugs.
References search_mums().
bit_vector** mum_make_bit_vectors (mum_results * results, struct iterator_state * state) [read]
Creates a list of two bit vectors based on the given strings, where marked bits correspond to starting indexes of MUM's inside the strings.
Parameters:
results The results of an iteration over a set of strings.
state Internal state of the iterator that performed the search.
Returns:
Bit vectors with starts of MUMs marked.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, wavelet_tree::get_num_bits, init_bit_vector(), and bit_vector::mark_bit.
Referenced by mum_print_bit_vectors(), and print_mums().
void mum_print_bit_vectors (char * string1, char * string2, mum_results * results, struct iterator_state * state)
Prints the bit vectors of the strings which show where MUMs occur to stdout.
Every time a MUM is found, the BWT index of the MUM is marked on both strings' bit vectors.
Parameters:
string1 The first string for which a bit vector is to be printed.
string2 The first string for which a bit vector is to be printed.
results The results of the iteration over the two strings.
state Internal state of the iterator that performed the search.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References mum_make_bit_vectors(), and print_bit_vector_with_string().
void print_bit_vector_with_string (char * string1, bit_vector * vector)
A simple function for printing a bit vector with the c-string that is related to it to stdout.
Parameters:
string1 The string related to the vector.
vector The bit vector to be printed.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::is_bit_marked.
Referenced by mum_print_bit_vectors().
void print_mums (char * string, mum_results * results, struct iterator_state * state)
Prints the indexes of the MUM in both strings, as well as the substring itself, to stdout.
Parameters:
string The string that is to be searched inside the MUM.
results Results of the iteration over a set of strings.
state The internal state of the iterator that performed the search.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References iterator_state::bwts, map_mum_triplets_to_string(), mum_make_bit_vectors(), and substring_from_string().
void search_mums (struct iterator_state * state, void * results)
Callback function given to double_iterate that determines if a substring is a MUM.
Parameters:
state The internal state of the iterator.
results A pointer to a region of memory containing the previous results of this callback function. Can safely be cast to mum_results if iterate was initialized using initialize_for_mums().
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
Doesn't differentiate between the $-characters.
References iterator_state::bwts, wavelet_tree::char_at, iterator_state::current, iterator_state::reverse_bwts, and iterator_state::threshold.
Referenced by initialize_for_mums().