BW4SA: src/core/rbwt.c File Reference
rbwt.c File Reference
Implementation of reversing a BWT.
#include "rbwt.h"
#include "s_to_bwt.h"
#include "../utils/wavelet_tree.h"
#include <stdlib.h>
#include <string.h>
Functions
char * reverse_string (const char *string, char *target, unsigned int length)
Reverses the direction of a string.
wavelet_tree * reverse_bwt (const char *string)
Creates the BWT of the reverse of the given string.
Detailed Description
Implementation of reversing a BWT.
See also:
rbwt.h
Author:
Paula Lehtola, Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
wavelet_tree* reverse_bwt (const char * string) [read]
Creates the BWT of the reverse of the given string.
Parameters:
string The c-string to be reversed and have a BWT created for.
Returns:
The BWT of the reversed string represented as a wavelet tree.
Author:
Paula Lehtola, Max Sandberg (REXiator)
Bug:
No known bugs.
References reverse_string(), and s_to_bwt().
Referenced by initialize_iterator(), and single_iterate().
char* reverse_string (const char * string, char * target, unsigned int length)
Reverses the direction of a string.
Parameters:
string The c-string to be reversed.
target A c-string where the result should be stored. If NULL, a new c-string will be allocated and returned.
length Length of the string to be reversed (and thus also the length of the reversed string).
Returns:
The reversed string.
Author:
Paula Lehtola, Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by reverse_bwt().