BW4SA: src/core/s_to_bwt.h File Reference
s_to_bwt.h File Reference
A function for determining the BWT of a c-string.
Typedefs
typedef unsigned char uchar
Functions
struct wavelet_tree * s_to_bwt (uchar *string)
Performs Burrows-Wheeler transform on the given string.
Detailed Description
A function for determining the BWT of a c-string.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
struct wavelet_tree* s_to_bwt (uchar * string) [read]
Performs Burrows-Wheeler transform on the given string.
Parameters:
string The string on which the Burrows-Wheeler transform is applied.
Returns:
The BWT of the string, represented as a wavelet tree.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
References create_wavelet_tree().
Referenced by draw_suffix_tree(), initialize_iterator(), and reverse_bwt().