BW4SA: bit_vector Struct Reference
bit_vector Struct Reference
A structure for storing the bit vector and its manipulation-functions.
#include <bit_vector.h>
Data Fields
unsigned int * vector
unsigned int length
unsigned int filler_bits
struct bit_vector *(* mark_bit)(struct bit_vector *vector, unsigned int pos)
Function pointer to a function that flags the bit at position pos inside the bit vector vector.
struct bit_vector *(* unmark_bit)(struct bit_vector *vector, unsigned int pos)
Function pointer to a function that unflags the bit at position pos inside the bit vector vector.
int(* is_bit_marked)(const struct bit_vector *vector, unsigned int pos)
Function pointer to a function that checks if the bit at position pos is marked inside the bit vector vector.
unsigned int(* rank)(const struct bit_vector *vector, unsigned int start, unsigned int end)
Function pointer to a function that counts the number of set bits inside a vector inside the interval start -> end.
unsigned int(* get_length)(const struct bit_vector *vector)
Function pointer to a function that returns the number of bits used by the bit vector supplied as parameter.
Detailed Description
A structure for storing the bit vector and its manipulation-functions.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Field Documentation
unsigned int(* bit_vector::get_length)(const struct bit_vector *vector)
Function pointer to a function that returns the number of bits used by the bit vector supplied as parameter.
Parameters:
vector The vector for which a length should be determined.
Returns:
The number of bits used by the vector supplied as parameter.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by determine_substrings(), get_num_bits_tree(), init_bit_vector(), print_bit_vector(), and rank_query().
int(* bit_vector::is_bit_marked)(const struct bit_vector *vector, unsigned int pos)
Function pointer to a function that checks if the bit at position pos is marked inside the bit vector vector.
Parameters:
vector A bit vector that is to be checked.
pos Position of the bit whose state is to be checked.
Returns:
1 if the bit is set, 0 otherwise.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by determine_substrings(), init_bit_vector(), map_maximal_repeats_to_string(), marked_bits_on_bit_vector(), print_bit_vector_with_string(), print_leaves_recursively(), rank_query(), update_position_in_triplets(), and wavelet_char_at().
struct bit_vector*(* bit_vector::mark_bit)(struct bit_vector *vector, unsigned int pos) [read]
Function pointer to a function that flags the bit at position pos inside the bit vector vector.
Parameters:
vector A bit vector that is to be manipulated.
pos The position of the bit that is to be flagged.
Returns:
The manipulated bit vector.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_bit_vector(), init_bit_vector(), max_repeat_make_bit_vector(), mem_make_bit_vectors(), mum_make_bit_vectors(), and print_leaves_recursively().
unsigned int(* bit_vector::rank)(const struct bit_vector *vector, unsigned int start, unsigned int end)
Function pointer to a function that counts the number of set bits inside a vector inside the interval start -> end.
Parameters:
vector The vector whose set bits is to be counted.
start The index inside the vector from which the count should start.
end The index inside the vector where the count should end.
Returns:
The number of set bits between start and end, or 0 if start > end or vector is uninitialized.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by determine_substrings(), init_bit_vector(), is_interval_left_maximal(), is_reverse_interval_right_maximal(), wavelet_char_at(), and wavelet_rank_query().
struct bit_vector*(* bit_vector::unmark_bit)(struct bit_vector *vector, unsigned int pos) [read]
Function pointer to a function that unflags the bit at position pos inside the bit vector vector.
Parameters:
vector A bit vector that is to be manipulated.
pos The position of the bit that is to be unflagged.
Returns:
The manipulated bit vector.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by init_bit_vector().
The documentation for this struct was generated from the following file:
src/utils/bit_vector.h