BW4SA: wavelet_tree Struct Reference
wavelet_tree Struct Reference
A struct for storing a wavelet tree.
#include <wavelet_tree.h>
Data Fields
unsigned int(* get_num_bits)(const struct wavelet_tree *tree)
Returns the number of bits used by the bit vector of the root node (= length of the string from which the tree was created).
unsigned int(* get_alphabet_length)(const struct wavelet_tree *tree)
Returns the length of the alphabet used by the root node.
char *(* get_alphabet)(const struct wavelet_tree *tree)
Returns the alphabet used by the root node.
int(* rank)(const struct wavelet_tree *tree, char c, int start, int end)
Counts the number of occurrences of a character inside an interval of the string used to create the tree.
char(* char_at)(const struct wavelet_tree *tree, int index)
Returns the character at index index inside the original string.
unsigned int num_nodes
wavelet_node * nodes
Detailed Description
A struct for storing a wavelet tree.
This structure stores all the nodes of a wavelet tree, as well as function pointers to operations possible on the tree. Such operations include length of the root node, rank and char at.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Field Documentation
char(* wavelet_tree::char_at)(const struct wavelet_tree *tree, int index)
Returns the character at index index inside the original string.
Parameters:
tree The wavelet tree for which the character should be determined.
index The index of the character to be determined.
Returns:
The character at index index inside the tree, or NULL if index > length of string or index < 0.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree(), map_maximal_repeats_to_string(), search_mums(), and update_position_in_triplets().
char*(* wavelet_tree::get_alphabet)(const struct wavelet_tree *tree)
Returns the alphabet used by the root node.
Parameters:
tree The tree whose alphabet is to be returned.
Returns:
The alphabet used by the root node of the tree.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree().
unsigned int(* wavelet_tree::get_alphabet_length)(const struct wavelet_tree *tree)
Returns the length of the alphabet used by the root node.
Parameters:
tree The tree for which the alphabet length should be determined.
Returns:
The length of the alphabet.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree(), initialize_iterator(), and list_mem_candidates().
unsigned int(* wavelet_tree::get_num_bits)(const struct wavelet_tree *tree)
Returns the number of bits used by the bit vector of the root node (= length of the string from which the tree was created).
Parameters:
tree The tree for which the length should be determined.
Returns:
Returns the length of the original string.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree(), double_iterate(), map_maximal_repeats_to_string(), map_mem_triplets_to_string(), map_mum_triplets_to_string(), max_repeat_make_bit_vector(), mem_make_bit_vectors(), mum_make_bit_vectors(), single_iterate(), update_position_in_triplets(), wavelet_root_char_at(), and wavelet_root_rank_query().
int(* wavelet_tree::rank)(const struct wavelet_tree *tree, char c, int start, int end)
Counts the number of occurrences of a character inside an interval of the string used to create the tree.
Parameters:
tree The tree for which the count should be done.
c The character to be counted.
start The starting index of the count.
end The ending index of the count.
Returns:
The number of occurrences of character c between indices start and end inside the wavelet tree.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree().
The documentation for this struct was generated from the following file:
src/utils/wavelet_tree.h