BW4SA: src/core/substring_stack.c File Reference
substring_stack.c File Reference
Implementation of the substring stack.
#include "substring_stack.h"
#include "../utils/structs.h"
#include <stdlib.h>
#include <stdio.h>
Functions
substring_stack * create_stack (int initial_size)
Creates an empty stack with given initial size.
void double_size (substring_stack *stack)
A function that doubles the size of given stack.
void push (substring_stack *stack, substring *substr)
Pushes given element onto given stack.
substring * pop (substring_stack *stack)
Pops and removes the top-most element from a stack.
void free_stack (substring_stack *stack)
Frees an entire stack structure and all data connected to it.
Detailed Description
Implementation of the substring stack.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
substring_stack* create_stack (int initial_size)
Creates an empty stack with given initial size.
Parameters:
initial_size Initial stack size.
Returns:
Pointer to the new empty stack.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by initialize_iterator().
void double_size (substring_stack * stack)
A function that doubles the size of given stack.
Parameters:
stack The stack whose size is to be doubled.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by push().
void free_stack (substring_stack * stack) [inline]
Frees an entire stack structure and all data connected to it.
Parameters:
stack The stack to be freed.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
substring* pop (substring_stack * stack) [read]
Pops and removes the top-most element from a stack.
Parameters:
stack The stack from which the top-most element is to be popped.
Returns:
A pointer to the popped substring.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by double_iterate(), and single_iterate().
void push (substring_stack * stack, struct substring * substr)
Pushes given element onto given stack.
Parameters:
stack The stack onto which the substring should be pushed.
substr The substring to be pushed onto the stack.
Author:
Topi Paavilainen, Max Sandberg (REXiator)
Bug:
No known bugs.
References double_size().
Referenced by double_iterate(), and single_iterate().