BW4SA: src/utils/utils.c File Reference
utils.c File Reference
Implementation of the utility-algorithms.
#include "utils.h"
#include "bit_vector.h"
#include "wavelet_tree.h"
#include "structs.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
Functions
void swap (void *arr, unsigned int entry_size, int i, int j, void *swap_area)
Simple swap-function.
void quicksort (void *arr, unsigned int entry_size, unsigned int a, unsigned int b, void *swap_area)
The implementation of the quicksort-algorithm.
void quick_sort (void *arr, unsigned int arr_size, unsigned int entry_size)
Standard generic quicksort-implementation.
void print_bits (unsigned int mask)
Prints the bits of an unsigned integer to stdout.
void string_swap (char **a, char **b)
Simple swap-function.
void string_quicksort (char **strings, unsigned int a, unsigned int b)
Quicksort for an array of strings.
void string_quick_sort (char **strings, unsigned int arr_size)
Quicksort for an array of strings.
char * determine_alphabet (const char *string)
Determines the alphabet used by a string.
int binary_search (const void *arr, const void *key, unsigned int entry_size, int max, int min)
A generic implementation of a standard binary search-algorithm.
void print_bit_vector (bit_vector *vector)
A simple function that prints a bit vector and its contents to stdout.
void print_wavelet_node (wavelet_node *node)
A simple function that prints a node in a wavelet tree to stdout.
void print_wavelet_tree (wavelet_tree *tree)
Prints an entire wavelet tree to stdout.
char * substring_from_string (char *string, int position, int length)
Returns a substring of a string starting at position with length length.
bit_vector * create_runs_vector (const wavelet_tree *string, bit_vector *target)
substring * create_substring (interval *normal, interval *reverse, int length, substring *target)
Creates a substring struct from interval and length.
interval * update_reverse_interval (interval *inter, interval *normal, const char *alphabet, unsigned int alphabet_length, const int *c_array, const char c, interval *target)
Detailed Description
Implementation of the utility-algorithms.
See also:
utils.h
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
int binary_search (const void * arr, const void * key, unsigned int entry_size, int max, int min)
A generic implementation of a standard binary search-algorithm.
Parameters:
arr A pointer to an array of any type upon which the search is to be done.
key A pointer to a value that is to be found inside the array.
entry_size The size of the type of the key.
max The maximum index that is to be searched.
min The minimum index that is to be searched.
Returns:
Returns the index of the key inside the array, or -1 if the array doesn't contain the key.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_bit_vector(), update_reverse_interval(), wavelet_rank_query(), and wavelet_root_rank_query().
substring* create_substring (struct interval * normal, struct interval * reverse, int length, struct substring * target) [read]
Creates a substring struct from interval and length.
Parameters:
interval in normal BWT
interval in the BWT of the reverse of the string
length of substring
Returns:
pointer to a new substring struct
Referenced by double_iterate(), list_mem_candidates(), and single_iterate().
char* determine_alphabet (const char * string)
Determines the alphabet used by a string.
Determines the alphabet used by a string. The alphabet of a string is defined as the characters used in the string, including all special characters.
Parameters:
string The string from which the alphabet should be deduced.
Returns:
The alphabet used by the string.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree().
void print_bit_vector (struct bit_vector * vector)
A simple function that prints a bit vector and its contents to stdout.
Parameters:
vector The bit vector that is to be printed.
See also:
bit_vector.h
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::get_length, and print_bits().
Referenced by print_wavelet_node().
void print_bits (unsigned int mask)
Prints the bits of an unsigned integer to stdout.
Parameters:
mask The unsigned integer whose bits are to be printed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by print_bit_vector().
void print_wavelet_node (struct wavelet_node * node)
A simple function that prints a node in a wavelet tree to stdout.
Parameters:
node The node that is to be printed.
See also:
wavelet_tree.h
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References print_bit_vector().
Referenced by print_wavelet_tree().
void print_wavelet_tree (struct wavelet_tree * tree)
Prints an entire wavelet tree to stdout.
Prints the contents of an entire wavelet tree, printing one level of depth at a time.
Parameters:
tree The wavelet tree to be printed.
See also:
wavelet_tree.h
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References print_wavelet_node().
void quick_sort (void * arr, unsigned int arr_size, unsigned int entry_size)
Standard generic quicksort-implementation.
This is a standard quicksort-algorithm that can be used for any data-type. It sorts the contents of an array in ascending order.
Parameters:
arr Pointer to the array to be sorted.
arr_size Size of the array to be sorted.
entry_size Size of the individual entries in the array.
Returns:
Returns the sorted array.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References quicksort().
Referenced by create_wavelet_tree(), and map_maximal_repeats_to_string().
void quicksort (void * arr, unsigned int entry_size, unsigned int a, unsigned int b, void * swap_area)
The implementation of the quicksort-algorithm.
Parameters:
arr Pointer to the array that is to be sorted.
entry_size Size of the individual entries in the array.
a Index to the first entry to be sorted.
b Index to the last entry to be sorted.
See also:
utils.h::quick_sort
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References swap().
Referenced by quick_sort().
void string_quick_sort (char ** strings, unsigned int arr_size)
Quicksort for an array of strings.
Parameters:
strings An array of pointers to strings.
arr_size Size of the array to be sorted.
See also:
utils.h::quick_sort
Author:
Paula Lehtola, Max Sandberg (REXiator)
Bug:
No known bugs.
References string_quicksort().
Referenced by distinct_substrings().
void string_quicksort (char ** strings, unsigned int a, unsigned int b)
Quicksort for an array of strings.
Parameters:
strings Array of pointers to strings.
a Index of the first entry to be sorted.
b index of the last entry to be sorted.
See also:
utils.h::quick_sort
Author:
Paula Lehtola, Max Sandberg (REXiator)
Bug:
No known bugs.
References string_swap().
Referenced by string_quick_sort().
void string_swap (char ** a, char ** b)
Simple swap-function.
Swaps the position of two strings in an array.
Parameters:
a Pointer to a pointer to a string to be swapped.
b Pointer to a pointer to another string to be swapped.
See also:
utils.h::string_quick_sort
Author:
Paula Lehtola, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by string_quicksort().
char* substring_from_string (char * string, int position, int length)
Returns a substring of a string starting at position with length length.
Parameters:
string The whole string.
position Starting position of the substring.
length Length of the substring.
Returns:
A substring of the string supplied as parameter.
Author:
Lassi Vapaakallio, Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by print_mems(), and print_mums().
void swap (void * arr, unsigned int entry_size, int i, int j, void * swap_area)
Simple swap-function.
Swaps the position of two entries in an array.
Parameters:
arr Pointer to the array is to be manipulated.
entry_size Size of the entries that are to be swapped.
i Index of the first entry.
j Index of the second entry.
See also:
utils.h::quick_sort
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by quicksort().
interval* update_reverse_interval (struct interval * inter, struct interval * normal, const char * alphabet, unsigned int alphabet_length, const int * c_array, const char c, struct interval * target) [read]
Updates the interval in the BWT of the reverse of the string
Parameters:
inter interval of the mother node
normal updated BWT interval in this node
alphabet alphabet of the interval
alphabet_length length of the alphabet in the interval
c_array C array of the interval
c extension character
target A interval where the results should be stored. If NULL, a new interval will be created and returned.
Returns:
a new updated Interval struct in the BWT of the reverse of the string
References binary_search().
Referenced by double_iterate(), list_mem_candidates(), and single_iterate().