BW4SA: src/utils/wavelet_tree.h File Reference
wavelet_tree.h File Reference
An implementation of a standard wavelet tree-structure.
#include "bit_vector.h"
Data Structures
struct wavelet_node
A simple struct for storing a node of a wavelet tree.
struct wavelet_tree
A struct for storing a wavelet tree.
Typedefs
typedef struct wavelet_node wavelet_node
A simple struct for storing a node of a wavelet tree.
typedef struct wavelet_tree wavelet_tree
A struct for storing a wavelet tree.
Functions
wavelet_tree * create_wavelet_tree (const char *string)
An algorithm that creates a wavelet tree from a string.
void free_wavelet_tree_internals (wavelet_tree *tree)
A function for freeing the internal variables used by a wavelet tree without freeing the tree itself.
void free_wavelet_tree (wavelet_tree *tree)
Frees the memory used by an entire wavelet tree.
Detailed Description
An implementation of a standard wavelet tree-structure.
This file contains the implementation of a standard wavelet tree- structure. A wavelet tree allows for better compression of strings and better performance on rank-queries, and thus much improved performance for the program overall.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Data Structure Documentation
struct wavelet_node
A simple struct for storing a node of a wavelet tree.
This struct stores all the necessary data of a node inside a wavelet tree, including the bit vector, the alphabet used and locations of its children (if any).
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Data Fields
char * alphabet
unsigned int alphabet_length
unsigned int children
char * string
bit_vector vector
Typedef Documentation
typedef struct wavelet_node wavelet_node
A simple struct for storing a node of a wavelet tree.
This struct stores all the necessary data of a node inside a wavelet tree, including the bit vector, the alphabet used and locations of its children (if any).
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
typedef struct wavelet_tree wavelet_tree
A struct for storing a wavelet tree.
This structure stores all the nodes of a wavelet tree, as well as function pointers to operations possible on the tree. Such operations include length of the root node, rank and char at.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
wavelet_tree* create_wavelet_tree (const char * string)
An algorithm that creates a wavelet tree from a string.
This algorithm recursively creates a wavelet tree from the string supplied as parameter.
Parameters:
string The string of characters from which a wavelet tree is to be constructed.
Returns:
A structure containing the wavelet tree, or NULL if the string is uninitialized.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References wavelet_tree::char_at, create_children(), determine_alphabet(), wavelet_tree::get_alphabet, wavelet_tree::get_alphabet_length, get_alphabet_length_tree(), get_alphabet_tree(), wavelet_tree::get_num_bits, get_num_bits_tree(), init_node(), quick_sort(), wavelet_tree::rank, wavelet_root_char_at(), and wavelet_root_rank_query().
Referenced by s_to_bwt().
void free_wavelet_tree (wavelet_tree * tree)
Frees the memory used by an entire wavelet tree.
This algorithm frees an entire wavelet tree. It also frees the alphabet used by the wavelet tree, but leaves the original string from which the tree was created intact.
Parameters:
tree The wavelet tree to be freed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References free_wavelet_tree_internals().
Referenced by draw_suffix_tree().
void free_wavelet_tree_internals (wavelet_tree * tree)
A function for freeing the internal variables used by a wavelet tree without freeing the tree itself.
Parameters:
tree The tree whose internals should be freed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References free_subtree().
Referenced by free_iterator_state(), and free_wavelet_tree().