BW4SA: src/utils/wavelet_tree.c File Reference
wavelet_tree.c File Reference
Implementation of the wavelet tree-structure.
#include "wavelet_tree.h"
#include "utils.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdio.h>
#include <limits.h>
Functions
int wavelet_rank_query (const wavelet_tree *tree, unsigned int curr_node, char c, int start, int end)
The implementation for the rank query on a wavelet tree.
int wavelet_root_rank_query (const wavelet_tree *tree, char c, int start, int end)
The rank query that is called from inside the tree.
char wavelet_char_at (const wavelet_tree *tree, unsigned int curr_node, int index)
Returns the character at a certain index inside a wavelet tree.
char wavelet_root_char_at (const wavelet_tree *tree, int index)
The root function of char at that is called from the tree.
unsigned int get_num_bits_tree (const wavelet_tree *tree)
A function that returns the number of bits inside the bit vector of the root node (= length of the string).
unsigned int get_alphabet_length_tree (const wavelet_tree *tree)
A function that returns the length of the alphabet of the root node.
char * get_alphabet_tree (const wavelet_tree *tree)
A function that returns the alphabet of the root node.
wavelet_node * init_node (wavelet_node *node, const char *string, const char *alphabet, unsigned int alphabet_length)
A simple function for initializing the values in a wavelet node.
bit_vector * create_bit_vector (bit_vector *vector, const char *string, const char *alphabet, unsigned int alphabet_length)
Constructs a bit vector based on the alphabet of the node.
char ** determine_substrings (const wavelet_tree *tree, unsigned int parent, char **string_arr, const char *string)
Splits a string into two substrings.
int create_children (wavelet_tree *tree, unsigned int curr_node, unsigned int next, const char *string)
Recursively creates children for a node.
wavelet_tree * create_wavelet_tree (const char *string)
An algorithm that creates a wavelet tree from a string.
void free_subtree (wavelet_tree *tree, unsigned int node)
Frees a wavelet (sub)tree.
void free_wavelet_tree_internals (wavelet_tree *tree)
A function for freeing the internal variables used by a wavelet tree without freeing the tree itself.
void free_wavelet_tree (wavelet_tree *tree)
Frees the memory used by an entire wavelet tree.
Detailed Description
Implementation of the wavelet tree-structure.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Function Documentation
bit_vector* create_bit_vector (bit_vector * vector, const char * string, const char * alphabet, unsigned int alphabet_length)
Constructs a bit vector based on the alphabet of the node.
This algorithm creates a bit vector with every character in the alphabet of the node marked as a 1 inside the bit vector and all other characters marked as 0.
Parameters:
vector The bit vector that is to be initialized.
string The string for which a bit vector is created.
alphabet The alphabet used by the string.
alphabet_length The length of the alphabet used by the string.
Returns:
Returns an initialized bit vector based on the string and alphabet supplied as parameters, or NULL if either string is uninitialized or the vector couldn't be initialized.
See also:
bit_vector.h
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References binary_search(), init_bit_vector(), and bit_vector::mark_bit.
Referenced by create_children().
int create_children (wavelet_tree * tree, unsigned int curr_node, unsigned int next, const char * string)
Recursively creates children for a node.
This algorithm populates the wavelet tree. It takes an initialized node as parameter for which it creates a bit vector and any possible children. If children are created, it will recursively call itself for the children. Otherwise it will return the index where the next node should be placed inside the tree.
Parameters:
tree The wavelet tree that is being populated.
curr_node The index of the node for which a bit vector and children is to be created.
next Index of the next free space inside the wavelet tree.
string The substring used by the current node.
Returns:
The next free index inside the wavelet tree.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References create_bit_vector(), determine_substrings(), and init_node().
Referenced by create_wavelet_tree().
wavelet_tree* create_wavelet_tree (const char * string)
An algorithm that creates a wavelet tree from a string.
This algorithm recursively creates a wavelet tree from the string supplied as parameter.
Parameters:
string The string of characters from which a wavelet tree is to be constructed.
Returns:
A structure containing the wavelet tree, or NULL if the string is uninitialized.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References wavelet_tree::char_at, create_children(), determine_alphabet(), wavelet_tree::get_alphabet, wavelet_tree::get_alphabet_length, get_alphabet_length_tree(), get_alphabet_tree(), wavelet_tree::get_num_bits, get_num_bits_tree(), init_node(), quick_sort(), wavelet_tree::rank, wavelet_root_char_at(), and wavelet_root_rank_query().
Referenced by s_to_bwt().
char** determine_substrings (const wavelet_tree * tree, unsigned int parent, char ** string_arr, const char * string)
Splits a string into two substrings.
This algorithm splits a string into two substrings by taking all the 0-marked characters in the bit vector of the parent and putting them in one string and the 1-marked characters into another string.
Parameters:
tree The wavelet tree where the parent node resides.
parent The index of the parent node inside the wavelet tree from which a new set of substrings should be determined.
string_arr An array of strings with space for 2 strings.
string The string that is to be split.
Returns:
An array of the two constructed substrings.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::get_length, bit_vector::is_bit_marked, and bit_vector::rank.
Referenced by create_children().
void free_subtree (wavelet_tree * tree, unsigned int node)
Frees a wavelet (sub)tree.
This algorithm frees a wavelet node and all of it's descendants. It does not free the alphabet used by the wavelet tree but it does break the link between the parent node and the subtree that is being freed, so it should be used with caution.
Parameters:
tree The wavelet tree where the subtree resides.
node The index of the root of the subtree that is to be freed.
See also:
free_wavelet_tree
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by free_wavelet_tree_internals().
void free_wavelet_tree (wavelet_tree * tree)
Frees the memory used by an entire wavelet tree.
This algorithm frees an entire wavelet tree. It also frees the alphabet used by the wavelet tree, but leaves the original string from which the tree was created intact.
Parameters:
tree The wavelet tree to be freed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References free_wavelet_tree_internals().
Referenced by draw_suffix_tree().
void free_wavelet_tree_internals (wavelet_tree * tree)
A function for freeing the internal variables used by a wavelet tree without freeing the tree itself.
Parameters:
tree The tree whose internals should be freed.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References free_subtree().
Referenced by free_iterator_state(), and free_wavelet_tree().
unsigned int get_alphabet_length_tree (const wavelet_tree * tree)
A function that returns the length of the alphabet of the root node.
Parameters:
tree The tree for which the alphabet length should be determined.
Returns:
The length of the longest alphabet in the tree.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree().
char* get_alphabet_tree (const wavelet_tree * tree)
A function that returns the alphabet of the root node.
Parameters:
tree The tree for which the alphabet should be returned.
Returns:
The alphabet used by the root node.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_wavelet_tree().
unsigned int get_num_bits_tree (const wavelet_tree * tree)
A function that returns the number of bits inside the bit vector of the root node (= length of the string).
Parameters:
tree The wavelet tree for which the length of the root string is to be determined.
Returns:
The length of the string used by the root node.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::get_length.
Referenced by create_wavelet_tree().
wavelet_node* init_node (wavelet_node * node, const char * string, const char * alphabet, unsigned int alphabet_length)
A simple function for initializing the values in a wavelet node.
Parameters:
node The node that is to be initialized.
string The string used by the node.
alphabet Half of the alphabet used by the string of the node.
alphabet_length Length of the alphabet.
Returns:
An initialized wavelet node.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
Referenced by create_children(), and create_wavelet_tree().
char wavelet_char_at (const wavelet_tree * tree, unsigned int curr_node, int index)
Returns the character at a certain index inside a wavelet tree.
Parameters:
tree The tree that is to be searched.
curr_node The current node that is under search.
index The index of the character that is to be identified.
Returns:
The found character at the location.
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References bit_vector::is_bit_marked, and bit_vector::rank.
Referenced by wavelet_root_char_at().
int wavelet_rank_query (const wavelet_tree * tree, unsigned int curr_node, char c, int start, int end)
The implementation for the rank query on a wavelet tree.
The rank query on a wavelet tree works by recursively doing a rank function on a child of the current node based on if the character has been encoded as a 0 or a 1 in the current node. If end is larger than the size of the bit vector, the rank operation will be done for the entire length of the vector.
Parameters:
tree The wavelet tree on which the rank query is performed.
curr_node The node on which the rank query is currently operating on.
c The character for which the rank is to be found.
start The indec of the first character from which the rank query should start.
end The index up to which the rank query is going to be made inside the bit vector.
Returns:
Returns the number of occurrences of character c in a string.
See also:
wavelet_root_rank_query
bit_vector.c::rank_query
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References binary_search(), and bit_vector::rank.
Referenced by wavelet_root_rank_query().
char wavelet_root_char_at (const wavelet_tree * tree, int index)
The root function of char at that is called from the tree.
Parameters:
tree The tree that is to be searched.
index The index of the character that is to be recognized.
Returns:
The found character.
See also:
wavelet_char_at
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References wavelet_tree::get_num_bits, and wavelet_char_at().
Referenced by create_wavelet_tree().
int wavelet_root_rank_query (const wavelet_tree * tree, char c, int start, int end)
The rank query that is called from inside the tree.
The entry point for the rank query. Checks all parameters are within bounds and does an initial search for the character inside the root alphabet. If not found, 0 can be returned right away.
Parameters:
tree The wavelet tree upon which a rank query is to be made.
c The character that is to be counted.
start The starting index for the rank query.
end The ending index for the rank query.
Returns:
Returns the number of occurrences of character c between start and end.
See also:
wavelet_rank_query
Author:
Max Sandberg (REXiator)
Bug:
No known bugs.
References binary_search(), wavelet_tree::get_num_bits, and wavelet_rank_query().
Referenced by create_wavelet_tree().